name: zone_express
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.0
  video_player: ^2.10.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/images/user_img/
     - assets/images/delivery_img/
     - assets/images/courier_img/
     - assets/video/intro_video/intro_zone_express.mp4
     - assets/images/account_img/

  fonts:
     - family: PlusJakarta
       fonts:
         - asset: assets/fonts/PlusJakartaSans-Medium.ttf
     - family: WorkSans
       fonts:
         - asset: assets/fonts/WorkSans-Medium.ttf